### ISSUE TITLE
Performance Cops will be extracted since v0.68.0

### ISSUE THREAD

**Issue by sue445** [onk/onkcop#61]
# Context
Performance Cops will be extracted since v0.68.0

* https://github.com/rubocop-hq/rubocop/pull/6845
* http://koic.hatenablog.com/entry/extract-performance-cops-from-rubocop-core (ja)

But `onkcop` includes `Performance` cop setting and `onkcop` will implicitly depend on `rubocop-performance`
https://github.com/onk/onkcop/blob/v0.53.0.3/config/rubocop.yml#L166-L171

Which of the following do you like?

# Plan A
Add `rubocop-performance` to `onkcop` as runtime dependency

# Plan B
Remove `Performance/Casecmp` from `config/rubocop.yml`

# Plan C
Other

**Comment by onk** [comment]
I plan to extract performance cop settings into a separate file, just as `config/rails.yml`.
