### ISSUE TITLE
rubocop config is outdated

### ISSUE THREAD

**Issue by ha-clipline** [onk/onkcop#68]
Error: The `Layout/IndentArray` cop has been renamed to `Layout/IndentFirstArrayElement`.
(obsolete configuration found in /usr/local/bundle/gems/onkcop-0.53.0.3/config/rubocop.yml, please update it)
The `Layout/IndentHash` cop has been renamed to `Layout/IndentFirstHashElement`.
(obsolete configuration found in /usr/local/bundle/gems/onkcop-0.53.0.3/config/rubocop.yml, please update it)

Please check and fix it !

**Comment by onk** [comment]
Apologies for a late reply.
v1.0.0.0 released.
